constant.env: local-yaml

spring:
  datasource:
#    url: jdbc:h2:~/checkmate
    url: jdbc:h2:tcp://localhost/~/checkmate
    username: sa
    password:
    driver-class-name: org.h2.Driver

security.jwt.token:
  secret-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIiLCJuYW1lIjoiSm9obiBEb2UiLCJpYXQiOjE1MTYyMzkwMjJ9.ih1aovtQShabQ7l0cINw4k1fagApg3qLWiB8Kt59Lno
  expire-length: 3600000
